adding copilot check manifest.yaml files

diff --git a/.github/workflows/bootstrap-copilot-project.yml b/.github/workflows/bootstrap-copilot-project.yml
--- a/.github/workflows/bootstrap-copilot-project.yml
+++ b/.github/workflows/bootstrap-copilot-project.yml
@@ -86,96 +86,104 @@ jobs:
           git config --global user.email "pradeep.reddy@ryvalx.com"
           git config --global user.name "PradeepReddy019"
           git add -A  # Adds all changes, including untracked files
-          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          if ! git diff --exit-code; then
+            git commit -m "AWS Copilot config files (manifest.yml) generated by GitHub Actions Bot"
+          else
+            echo "No changes to commit."
+          fi
           git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
         shell: bash
 
-
-  create-copilot-staging-environment:
-    needs: [ init-copilot ]
-    runs-on: ubuntu-latest
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - name: Download Copilot CLI from Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: copilot-cli
-          path: /usr/local/bin
-
-      - name: Ensure Copilot is executable
-        run: chmod +x /usr/local/bin/copilot
-
-      - name: Configure AWS Credentials using OIDC
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
-          aws-region: us-east-1
-          audience: sts.amazonaws.com
-
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Pull latest changes
-        run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
-
-      - name: Check for existing Copilot Staging Environment
-        id: check_environment
+      - name: Verify that manifest.yml exists
         run: |
-          if copilot env show --name staging --json; then
-            echo "Environment exists."
-            echo "environment_exists=true" >> $GITHUB_ENV
-          else
-            echo "Environment does not exist."
-            echo "environment_exists=false" >> $GITHUB_ENV
-          fi
-
-      - name: Initialize Staging Environment
-        id: init-environment
-        if: env.environment_exists == 'false'
-        run: |
-          if ! copilot env init --name staging --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }}; then
-            echo "Failed to initialize environment."
-            exit 1
-          fi
-
-      - name: Deploy environment to staging
-        run: |
-          # Make sure we're in the correct working directory for Copilot (root of the project)
-          if [ ! -d "copilot" ]; then
-            echo "Copilot workspace not found! Initializing Copilot..."
-            copilot app init --name ocean-watch
-          else
-            echo "Copilot workspace exists."
-          fi
-
-          # Check if the service already exists in the Copilot workspace
-          if ! copilot svc show --name ocean-watch > /dev/null 2>&1; then
-            echo "Service ocean-watch does not exist. Initializing..."
-            copilot svc init --name ocean-watch --svc-type "Load Balanced Web Service"
-          else
-            echo "Service ocean-watch already exists."
-          fi
-
-          # Deploy the environment to staging
-          echo "Deploying environment to staging..."
-          copilot env deploy --name staging --force
-
-          # Deploy the service to the staging environment
-          echo "Deploying service ocean-watch to staging..."
-          copilot svc deploy --name ocean-watch --env staging --force
+          ls -al copilot/ocean-watch/manifest.yml
 
 
-      - name: Commit AWS Copilot Staging Config
-        if: env.environment_exists == 'false'
-        run: |
-          git config --global user.email "pradeep.reddy@ryvalx.com"
-          git config --global user.name "PradeepReddy019"
-          git add -A  # Adds all changes, including untracked files
-          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
-          git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
-        shell: bash
+  # create-copilot-staging-environment:
+  #   needs: [ init-copilot ]
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     id-token: write
+  #     contents: read
+  #   steps:
+  #     - name: Download Copilot CLI from Artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: copilot-cli
+  #         path: /usr/local/bin
+
+  #     - name: Ensure Copilot is executable
+  #       run: chmod +x /usr/local/bin/copilot
+
+  #     - name: Configure AWS Credentials using OIDC
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
+  #         aws-region: us-east-1
+  #         audience: sts.amazonaws.com
+
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+
+  #     - name: Pull latest changes
+  #       run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
+
+  #     - name: Check for existing Copilot Staging Environment
+  #       id: check_environment
+  #       run: |
+  #         if copilot env show --name staging --json; then
+  #           echo "Environment exists."
+  #           echo "environment_exists=true" >> $GITHUB_ENV
+  #         else
+  #           echo "Environment does not exist."
+  #           echo "environment_exists=false" >> $GITHUB_ENV
+  #         fi
+
+  #     - name: Initialize Staging Environment
+  #       id: init-environment
+  #       if: env.environment_exists == 'false'
+  #       run: |
+  #         if ! copilot env init --name staging --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }}; then
+  #           echo "Failed to initialize environment."
+  #           exit 1
+  #         fi
+
+  #     - name: Deploy environment to staging
+  #       run: |
+  #         # Make sure we're in the correct working directory for Copilot (root of the project)
+  #         if [ ! -d "copilot" ]; then
+  #           echo "Copilot workspace not found! Initializing Copilot..."
+  #           copilot app init --name ocean-watch
+  #         else
+  #           echo "Copilot workspace exists."
+  #         fi
+
+  #         # Check if the service already exists in the Copilot workspace
+  #         if ! copilot svc show --name ocean-watch > /dev/null 2>&1; then
+  #           echo "Service ocean-watch does not exist. Initializing..."
+  #           copilot svc init --name ocean-watch --svc-type "Load Balanced Web Service"
+  #         else
+  #           echo "Service ocean-watch already exists."
+  #         fi
+
+  #         # Deploy the environment to staging
+  #         echo "Deploying environment to staging..."
+  #         copilot env deploy --name staging --force
+
+  #         # Deploy the service to the staging environment
+  #         echo "Deploying service ocean-watch to staging..."
+  #         copilot svc deploy --name ocean-watch --env staging --force
+
+
+  #     - name: Commit AWS Copilot Staging Config
+  #       if: env.environment_exists == 'false'
+  #       run: |
+  #         git config --global user.email "pradeep.reddy@ryvalx.com"
+  #         git config --global user.name "PradeepReddy019"
+  #         git add -A  # Adds all changes, including untracked files
+  #         git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+  #         git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
+  #       shell: bash
 
   # create-copilot-production-environment:
   #   needs: [ create-copilot-staging-environment ]
