adding the staging enviornment

diff --git a/.github/workflows/bootstrap-copilot-project.yml b/.github/workflows/bootstrap-copilot-project.yml
--- a/.github/workflows/bootstrap-copilot-project.yml
+++ b/.github/workflows/bootstrap-copilot-project.yml
@@ -80,72 +80,73 @@ jobs:
         if: env.app_exists == 'false'
         run: copilot app init ocean-watch --resource-tags program=Oceans,project=OceanWatch,application=OceanWatch
 
-      - name: Commit AWS Copilot Application Config
-        if: env.app_exists == 'false'
+      - name: Commit AWS Copilot Staging Config
+        if: env.environment_exists == 'false'
         run: |
-          git config --global user.email "action@github.com"
-          git config --global user.name "GitHub Action"
+          git config --global user.email "pradeep.reddy@ryvalx.com"
+          git config --global user.name "PradeepReddy019"
           git add -A  # Adds all changes, including untracked files
           git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
           git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
         shell: bash
 
-  # create-copilot-staging-environment:
-  #   needs: [ init-copilot ]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Download Copilot CLI from Artifacts
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: copilot-cli
-  #         path: /usr/local/bin
 
-  #     - name: Ensure Copilot is executable
-  #       run: chmod +x /usr/local/bin/copilot
+  create-copilot-staging-environment:
+    needs: [ init-copilot ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download Copilot CLI from Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: copilot-cli
+          path: /usr/local/bin
 
-  #     - name: Configure AWS Credentials using OIDC
-  #       uses: aws-actions/configure-aws-credentials@v2
-  #       with:
-  #         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
-  #         aws-region: us-east-1
-  #         role-duration-seconds: 1800
-  #         output-credentials: true
+      - name: Ensure Copilot is executable
+        run: chmod +x /usr/local/bin/copilot
 
-  #     - name: Checkout Repository
-  #       uses: actions/checkout@v4
+      - name: Configure AWS Credentials using OIDC
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
+          aws-region: us-east-1
+          role-duration-seconds: 1800
+          output-credentials: true
 
-  #     - name: Pull latest changes
-  #       run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-  #     - name: Check for existing Copilot Staging Environment
-  #       id: check_environment
-  #       run: |
-  #         if copilot env show --name staging --json; then
-  #           echo "Environment exists."
-  #           echo "environment_exists=true" >> $GITHUB_ENV
-  #         else
-  #           echo "Environment does not exist."
-  #           echo "environment_exists=false" >> $GITHUB_ENV
-  #         fi
+      - name: Pull latest changes
+        run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
 
-  #     - name: Initialize Staging Environment
-  #       id: init-environment
-  #       if: env.environment_exists == 'false'
-  #       run: |
-  #         if ! copilot env init --name staging --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
-  #           echo "Failed to initialize environment."
-  #           exit 1
-  #         fi
+      - name: Check for existing Copilot Staging Environment
+        id: check_environment
+        run: |
+          if copilot env show --name staging --json; then
+            echo "Environment exists."
+            echo "environment_exists=true" >> $GITHUB_ENV
+          else
+            echo "Environment does not exist."
+            echo "environment_exists=false" >> $GITHUB_ENV
+          fi
 
-  #     - name: Commit AWS Copilot Staging Config
-  #       if: env.environment_exists == 'false'
-  #       run: |
-  #         git config --global user.email "action@github.com"
-  #         git config --global user.name "GitHub Action"
-  #         git add -A  # Adds all changes, including untracked files
-  #         git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
-  #         git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
-  #       shell: bash
+      - name: Initialize Staging Environment
+        id: init-environment
+        if: env.environment_exists == 'false'
+        run: |
+          if ! copilot env init --name staging --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
+            echo "Failed to initialize environment."
+            exit 1
+          fi
+
+      - name: Commit AWS Copilot Staging Config
+        if: env.environment_exists == 'false'
+        run: |
+          git config --global user.email "pradeep.reddy@ryvalx.com"
+          git config --global user.name "PradeepReddy019"
+          git add -A  # Adds all changes, including untracked files
+          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+          git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
+        shell: bash
 
   # create-copilot-production-environment:
   #   needs: [ create-copilot-staging-environment ]
