commenting the production stage

diff --git a/.github/workflows/bootstrap-copilot-project.yml b/.github/workflows/bootstrap-copilot-project.yml
--- a/.github/workflows/bootstrap-copilot-project.yml
+++ b/.github/workflows/bootstrap-copilot-project.yml
@@ -87,116 +87,116 @@ jobs:
           git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
         shell: bash
 
-  create-copilot-staging-environment:
-    needs: [ init-copilot ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download Copilot CLI from Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: copilot-cli
-          path: /usr/local/bin
+  # create-copilot-staging-environment:
+  #   needs: [ init-copilot ]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download Copilot CLI from Artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: copilot-cli
+  #         path: /usr/local/bin
 
-      - name: Ensure Copilot is executable
-        run: chmod +x /usr/local/bin/copilot
+  #     - name: Ensure Copilot is executable
+  #       run: chmod +x /usr/local/bin/copilot
 
-      - name: Configure AWS Credentials using OIDC
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
-          aws-region: us-east-1
-          role-duration-seconds: 1800
-          output-credentials: true
+  #     - name: Configure AWS Credentials using OIDC
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
+  #         aws-region: us-east-1
+  #         role-duration-seconds: 1800
+  #         output-credentials: true
 
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
 
-      - name: Pull latest changes
-        run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
+  #     - name: Pull latest changes
+  #       run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
 
-      - name: Check for existing Copilot Staging Environment
-        id: check_environment
-        run: |
-          if copilot env show --name staging --json; then
-            echo "Environment exists."
-            echo "environment_exists=true" >> $GITHUB_ENV
-          else
-            echo "Environment does not exist."
-            echo "environment_exists=false" >> $GITHUB_ENV
-          fi
+  #     - name: Check for existing Copilot Staging Environment
+  #       id: check_environment
+  #       run: |
+  #         if copilot env show --name staging --json; then
+  #           echo "Environment exists."
+  #           echo "environment_exists=true" >> $GITHUB_ENV
+  #         else
+  #           echo "Environment does not exist."
+  #           echo "environment_exists=false" >> $GITHUB_ENV
+  #         fi
 
-      - name: Initialize Staging Environment
-        id: init-environment
-        if: env.environment_exists == 'false'
-        run: |
-          if ! copilot env init --name staging --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
-            echo "Failed to initialize environment."
-            exit 1
-          fi
+  #     - name: Initialize Staging Environment
+  #       id: init-environment
+  #       if: env.environment_exists == 'false'
+  #       run: |
+  #         if ! copilot env init --name staging --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
+  #           echo "Failed to initialize environment."
+  #           exit 1
+  #         fi
 
-      - name: Commit AWS Copilot Staging Config
-        if: env.environment_exists == 'false'
-        run: |
-          git config --global user.email "action@github.com"
-          git config --global user.name "GitHub Action"
-          git add -A  # Adds all changes, including untracked files
-          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
-          git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
-        shell: bash
+  #     - name: Commit AWS Copilot Staging Config
+  #       if: env.environment_exists == 'false'
+  #       run: |
+  #         git config --global user.email "action@github.com"
+  #         git config --global user.name "GitHub Action"
+  #         git add -A  # Adds all changes, including untracked files
+  #         git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+  #         git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
+  #       shell: bash
 
-  create-copilot-production-environment:
-    needs: [ create-copilot-staging-environment ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download Copilot CLI from Artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: copilot-cli
-          path: /usr/local/bin
+  # create-copilot-production-environment:
+  #   needs: [ create-copilot-staging-environment ]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download Copilot CLI from Artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: copilot-cli
+  #         path: /usr/local/bin
 
-      - name: Ensure Copilot is executable
-        run: chmod +x /usr/local/bin/copilot
+  #     - name: Ensure Copilot is executable
+  #       run: chmod +x /usr/local/bin/copilot
 
-      - name: Configure AWS Credentials using OIDC
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
-          aws-region: us-east-1
-          role-duration-seconds: 1800
-          output-credentials: true
+  #     - name: Configure AWS Credentials using OIDC
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Action_Role
+  #         aws-region: us-east-1
+  #         role-duration-seconds: 1800
+  #         output-credentials: true
 
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
 
-      - name: Pull latest changes
-        run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
+  #     - name: Pull latest changes
+  #       run: git pull origin ${{ github.head_ref }}  # Pull latest changes to ensure the local copy is up-to-date
 
-      - name: Check for existing Copilot Production Environment
-        id: check_environment
-        run: |
-          if copilot env show --name production --json; then
-            echo "Environment exists."
-            echo "environment_exists=true" >> $GITHUB_ENV
-          else
-            echo "Environment does not exist."
-            echo "environment_exists=false" >> $GITHUB_ENV
-          fi
+  #     - name: Check for existing Copilot Production Environment
+  #       id: check_environment
+  #       run: |
+  #         if copilot env show --name production --json; then
+  #           echo "Environment exists."
+  #           echo "environment_exists=true" >> $GITHUB_ENV
+  #         else
+  #           echo "Environment does not exist."
+  #           echo "environment_exists=false" >> $GITHUB_ENV
+  #         fi
 
-      - name: Initialize Production Environment
-        id: init-environment
-        if: env.environment_exists == 'false'
-        run: |
-          if ! copilot env init --name production --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
-            echo "Failed to initialize environment."
-            exit 1
-          fi
+  #     - name: Initialize Production Environment
+  #       id: init-environment
+  #       if: env.environment_exists == 'false'
+  #       run: |
+  #         if ! copilot env init --name production --app ocean-watch --default-config --region ${{ secrets.AWS_REGION }} --aws-session-token ${{ steps.creds.outputs.aws-session-token }}; then
+  #           echo "Failed to initialize environment."
+  #           exit 1
+  #         fi
 
-      - name: Commit AWS Copilot Production Config
-        if: env.environment_exists == 'false'
-        run: |
-          git config --global user.email "action@github.com"
-          git config --global user.name "GitHub Action"
-          git add -A  # Adds all changes, including untracked files
-          git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
-          git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
-        shell: bash
+  #     - name: Commit AWS Copilot Production Config
+  #       if: env.environment_exists == 'false'
+  #       run: |
+  #         git config --global user.email "action@github.com"
+  #         git config --global user.name "GitHub Action"
+  #         git add -A  # Adds all changes, including untracked files
+  #         git diff-index --quiet HEAD || git commit -m "AWS copilot configs generated by GitHub Actions Bot"
+  #         git push origin HEAD:${{ github.ref }}  # Ensure you're pushing to the correct branch
+  #       shell: bash
